### ISSUE TITLE
findOrfail() instead of find()

### ISSUE THREAD

**Issue by jcricaro** [prjkt/repofuck#116]
this way, we can catch`ModelNotFound` exceptions.

**Comment by makoru-hikage** [comment]
See commit 60faa6beb4444ddc44b07ce0d505cb27d3fe54ca

**Comment by makoru-hikage** [comment]
One probable reason is that responsibilities involving such exceptions are left to the end-users.

**Comment by rmrhz** [comment]
The problem of however is that the error message caught would result in naming the entity which is a bad move on my part.
