### ISSUE TITLE
The purpose of argument `$repoName` of `resolve` method in `Entities` is not clear

### ISSUE THREAD

**Issue by makoru-hikage** [prjkt/repofuck#66]
As I read the snippet below (L85-89 of `Entities.php`),

```
switch($entity)
        {
            case null && $this->hasValues($this->entities):
                return array_key_exists($repoName, $this->entities) ?
                    $this->entities[$repoName] : array_values($this->entities)[0];
            break;
```

it seems that something is amiss. 

Per my understanding of the code: "If the `$entity` is `null` and the `$entities` has elements, determine whether `$repoName` is a key in `$entities` or not. If it is, return its corresponding value, otherwise, the first element."

How will a repository name (`$repoName`) as an argument be used to return a entity(`Model`) object if only entities are allowed to be pushed (`push()`) into `$entities` property of `Entities` object? If the `$entity` argument of `resolve()` is enough to `resolve` an entity, what is the `$repoName` truly for?

**Comment by rmrhz** [comment]
Hmmm. For example if you're configuring the repository named `Users` and you have an entity named `User`. What the operation does is use `$this->entities['users']` if `users` as the array key exists in `$this->entities`. The case is entity names are singular and table names are in plural form.

If the plural form did not exist. It will return the first configured entity from the container.
