### ISSUE TITLE
Question: How shall I switch the current entity in v 0.2.0?

### ISSUE THREAD

**Issue by makoru-hikage** [prjkt/repofuck#92]
Assuming that the `entities` of the `Entities` object is defined as `['users', 'posts', 'comments' ]`, how shall I switch from `users` to `comments`? (Upon the instantiation of descendant of `Repofuck`, the first item of the array shall be always the current `$entity`)

How shall I use the soon-to-be-refactored `entity` to do my bidding?

**Comment by rmrhz** [comment]
I'll put up a documentation for usage.

**Comment by makoru-hikage** [comment]
Upon seeing the function, I see that there are two arguments to be supplied: the `$name` and `$closure`. The `$name` is the key name of the entity to be switched to.

Here are examples:
```
//Should I want to switch to comments
$repo->entity('comments');

//Should I want to switch to users then show all the users with posts 
$repo->entity('users', function($entity){
    return $entity->with('posts');
});
```

If you will notice, `entity()` is now like `prepare()`, `prepare()` has only one argument which is a `Closure`.  The `Closure` that you supply in `entity()` must have an argument that accepts a `Model` or a `Builder`, whilst the one for `prepare()` must have a `Repofuck`.
